version: 'v2.18.1'


services:
    weather-etl:
        build:
            context: ./weather_service
            dockerfile: Dockerfile
        image: weather_etl
        container_name: weather_etl
        volumes:
            - ./weather_service:/app
        environment:
            DATABASE_FILE: "/app/loader_data/SQL_DB/weather_data.db"
